[package]
name = "cdn"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
async-stream = "0.3.6"
futures = "0.3.31"
mime_guess = "2.0.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_default = "0.2.0"
serde_json = "1.0.143"
