on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Build Release
              run: cargo build --release

            - name: Copy to server
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_PORT }}
                  target: ${{ secrets.SERVER_TARGET_PATH }}
                  source: target/release/cdn,deploy

            - name: Restart service
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_PORT }}
                  script_path: deploy/deploy.sh
